### ISSUE TITLE
v2.4.2リリース作業

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1870]
## 要約
このチケットでリリース作業の進捗管理をします。

## 経緯
#1868 での問題報告を受けて、更新リリースを行います。

## タスクリスト
- [x] `release/v2.4.1` から `release/v2.4.2` を作って push
- [x] 問題の不具合を修正する feature ブランチを作って `release/v2.4.2` に対してPR送って merge(#1872)
- [x] 最新の `release/v2.4.2` から feature ブランチ作って、バージョン情報を更新するPR送って merge(#1873)
- [x] `v2.4.2` のタグを打つ。
- [x] (課題対応)「バージョン番号の最後の数字が意図通りに表示されていない」の対応が必要かどうか判断して、必要なら対策を行う(https://github.com/sakura-editor/sakura/issues/1870#issuecomment-1336364133)
- [x] v2.4.2リリース
- [x] sakura-editor.github.io更新(https://github.com/sakura-editor/sakura-editor.github.io/pull/73) 
- [x] (リリース後作業) masterのヘルプファイルのバージョンを更新する(#1875)
- [x] https://github.com/sakura-editor/changelog-sakura の artifacts を master の `CHANGELOG.md` に適用する。(#1877)

**Comment by berryzplus** [comment]
#1385のマージコミット(d884ae4)をv2.4.1にマージしたところ、ビルドが通りませんでした。

既にくじけそうです。

**Comment by berryzplus** [comment]
タグ打ってpushしました。 [5977eba](https://github.com/sakura-editor/sakura/commit/5977eba43cbe3d80e928ef360ed9bed82a856e08)

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/1873#issuecomment-1336363870

> レビューありがとうございます。進めてしまいます。
> 
> バージョン表記は変えているで問題はなさそうに思います。
> 
> v2.4.2.xxxのxxx部分はタグビルドのときだけ入る仕組みで、採番の基準も「Appveyorのビルド番号」から「Gitリポジトリの総コミット数」に変えていたと思います。

うまく動いてないように見えます。
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/45568989/job/ih4tvklv54dthp4d/artifacts

![image](https://user-images.githubusercontent.com/5567450/205484510-a7a8714c-754c-4bd5-8cf5-cd0e0c351b2a.png)

**Comment by berryzplus** [comment]
リリース作業ストップしました。

**Comment by berryzplus** [comment]
直すのそんなに難しくなさそうですがどうします？

v2.4.2で複数verのリリースをしないのであれば枝番がでてなくても問題はないと思います。
通し番号的なものが欲しい、というニーズがあるなら対応したほうが「よい」になります。
対応する場合、master側にも変更を適用しないといかんので余分にひと手間要ります。

**Comment by beru** [comment]
> v2.4.2で複数verのリリースをしないのであれば枝番がでてなくても問題はないと思います。
> 通し番号的なものが欲しい、というニーズがあるなら対応したほうが「よい」になります。
> 対応する場合、master側にも変更を適用しないといかんので余分にひと手間要ります。

v2.4.2で複数verのリリースはしない方が良いと思います。v2.4.2はリリースのアナウンスとかはまだされていないと思うので、ステータスとしてはまだリリースはされていないですよね？それであれば上書き（tagを削除して作り直し？）すれば良いのかなと。

個人的には4番目の通し番号はいらないと思います。4番目の通し番号があると、その分3番目とか2番目の通し番号の数値が上がりにくくなりそうです。

リリースしたけどミスっちゃたから短い間隔で再度リリースする、という場合に（まだv2.4.2リリースはされていないという認識ですが）3番目の通し番号の数値を上げるのに抵抗がある場合は、4番目の通し番号的なものを導入するのは有りかもしれません。ただし4番目の通し番号は「Gitリポジトリの総コミット数」なので、それと概念がぶつかってしまうと思います。

リリース呼称として下記のように扱うという事だけであれば問題無いと思います。ただ基本的には1,2,3番目の通し番号が同じ数値で再リリースはなるべくしない方が良いとは思います。

- v2.4.2 0th
- v2.4.2 1st
- v2.4.2 2nd
- v2.4.2 3rd
- v2.4.2 4th
- v2.4.2 5th
- .....

**Comment by berryzplus** [comment]
#1874 をマージしてtagを付けなおしました。 (https://github.com/sakura-editor/sakura/commit/a3e63915b3c3236a9f14fbb27a01cf7acb030f45)

**Comment by berryzplus** [comment]
CHANGELOG.md を masterに取り込む

[sakura-editor/changelog-sakura](https://github.com/sakura-editor/changelog-sakura) の artifacts の CHANGELOG.md
　↓
[sakura-editor/sakura](https://github.com/sakura-editor/sakura) の CHANGELOG.md

具体的にどうしたらいいか、固まったので保留中。

**Comment by m-tmatma** [comment]
> CHANGELOG.md を masterに取り込む
> 
> [sakura-editor/changelog-sakura](https://github.com/sakura-editor/changelog-sakura) の artifacts の CHANGELOG.md 　↓ [sakura-editor/sakura](https://github.com/sakura-editor/sakura) の CHANGELOG.md
> 
> 具体的にどうしたらいいか、固まったので保留中。

https://ci.appveyor.com/project/sakuraeditor/changelog-sakura/branch/master/artifacts
とかで  CHANGELOG.md をダウンロードして、master に適用する PR を投げるイメージですが、

2.4.2 のタグが、master とは別系統になっているので、
2.4.1 ～ 2.4.2 までの変更と
2.4.2 移行の変更とわかれてないですね。

**Comment by m-tmatma** [comment]
> CHANGELOG.md を masterに取り込む
> 
> [sakura-editor/changelog-sakura](https://github.com/sakura-editor/changelog-sakura) の artifacts の CHANGELOG.md 　↓ [sakura-editor/sakura](https://github.com/sakura-editor/sakura) の CHANGELOG.md
> 
> 具体的にどうしたらいいか、固まったので保留中。

https://github.com/sakura-editor/sakura/pull/1877

**Comment by berryzplus** [comment]
ありがとうございます。

全作業完了したので閉じます。
