### ISSUE TITLE
MinGW向けメイクファイルでサクラエディタをビルドできるようにする

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#349]
最近いれた修正の影響で、Makefileを使ったビルドができなくなっています。
とりあえず、ビルドできる状態に戻したいです。

https://github.com/sakura-editor/sakura/pull/306#issuecomment-411458900

- [x] svnrev ⇒ githashの対応をする #306
- [x] sakura_rc.rcをutf8に変換したことによる修正をする #306 
- [x] #288 で入れてしまった gcc に怒られる記述を訂正する
- [x] #303 で入れてしまった gcc に怒られる例外処理をなんとかする

ここまでやれれば、 #309 の準備に取り掛かれる目論見です。

----

### 8/24 追加タスク
- [x] MinGWビルドの情報を build.md に追加する #351
- [x] `mingw32-make clean` を動くようにする #351
- [ ] `mingw32-make` で デバッグビルド できるようにする
- [x] sakura_lang_en_US.dll の Makefile を更新する #369
- [ ] `mingw32-make` で sakura.exe と sakura_lang_en_US.dll をビルドするバッチを作る

**Comment by berryzplus** [comment]
コミットコメントにmarkdownを使えないのを失念していて、
コメントがおかしくなっているので修正します。

**Comment by berryzplus** [comment]
PRと間違ってissueにコメントしていたので、コメントの「Hide」を試してみました。

新しい状況があるので夜にまた更新します。

**Comment by berryzplus** [comment]
> 新しい状況があるので夜にまた更新します。

というわけで追加状況を報告します。

----

Debugができるよう試行錯誤した結果、
Eclipse4.7向けの `MinGW Makefiles` により、
GCC産サクラエディタで編集ウインドウを表示することに成功しました。
これにより、このissueの目標「MinGW向けメイクファイルで(ry」が怪しくなってきました。

起きた状況を箇条書きにしてみます。

* MinGW向けMakefileをデバッグ対応にする　→　できた。
  少し課題があるが対応自体は簡単。ただし、やっぱり動かない。
* MinGW向けMakefileデバッグ版をeclipseで開いてみる　→　できた。
  デバッグしているはずなのに、よく分からない箇所で落ちる現象に遭遇。
  この時点で、「実は64bit版では実績ないかも？」の事実に気付く。
  同時に、Makefileに指定している各種オプションが「誤っている可能性」にも気づく。
  用意したコミットを保留してcmake化の実験に動くことする。
* MinGW向け特化のCMakeLists.txtを作る　→　 #46 をベースにすることで意外と簡単にできた。
  作ったものは一旦手元においてある https://github.com/berryzplus/sakura/tree/feature/appveyor_test
  eclipse CDT で MinGW ビルドを成功させるには PATH を通す必要があった。
  CDT上でデバッグ実行してみたところ、一発で編集ウインドウが表示された。
  現状のMakefileの「誤っている可能性」のウラが取れた。
  少なくとも64bit向けに何か足りない設定がありそうだ。
  この時点で、このissueの目標「MinGW向けメイクファイルで(ry」の意義は失われた。

直接cmake化できるならMakefileをデバッグ対応にする必要はない。
また、sakura.exeとsakura_lang_en_US.dllをビルドするバッチはｍ_tmatmaさんがすでに用意してくれている。

上記「確認に使ったCMakeLists.txt」のつくりは雑なのでまだ少し課題が残っている。
「Makefileを動くように」よりも「CMakeLists.txtの完成度を上げる」のほうが有意義な気がする。

このissueは着地点を失ったので閉じることにする。

**Comment by m-tmatma** [comment]
> MinGW向け特化のCMakeLists.txtを作る　→　 #46 をベースにすることで意外と簡単にできた。

#378 で最新をベースに cmake 用の対応をあげました。
