### ISSUE TITLE
exuberant ctags を Universal ctags  に差し替えるか検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#450]
exuberant ctags を Universal ctags  に差し替えるか検討する

@k-takata
https://github.com/sakura-editor/sakura/issues/448#issuecomment-421735787

> 最近は [Universal ctags](https://github.com/universal-ctags/ctags) という後継があります。

@m-tmatma 
https://github.com/sakura-editor/sakura/issues/448#issuecomment-421737709

> https://github.com/universal-ctags/ctags を見る限り、
> まだリリースされたバージョンはなく、[絶賛開発中](https://hint.hateblo.jp/entry/2016/02/17/%E6%B0%97%E3%81%AB%E3%81%AA%E3%82%8B%E8%AA%A4%E7%94%A8) みたい。

### タスク一覧

- [x] #454 Universal ctags を組み込む
- [x] #458 ヘルプの説明を exuberant ctags → Universal ctags に変更する
- [ ]  ~~サクラエディタリリース時点で最新の [Universal ctags](https://github.com/universal-ctags/ctags-win32/releases) に差し替える~~ → #515 に分離

**Comment by m-tmatma** [comment]
@k-takata さん
https://github.com/universal-ctags/ctags/issues/660#issuecomment-305041878

Universal ctags の開発に参加してるんですね。

- いつ頃リリースされるか決まってますか?

**Comment by k-takata** [comment]
ドキュメントの typo 修正とか CI の立ち上げなどをやりましたが最近はあまりアクティブには参加してないですね…。
リリースはリーダーの @masatake さんの意向次第です。今のところ決まっていないようです。
なお、Win32用のバイナリは https://github.com/universal-ctags/ctags-win32 でデイリービルドを公開しています。

**Comment by m-tmatma** [comment]
> なお、Win32用のバイナリは https://github.com/universal-ctags/ctags-win32 でデイリービルドを公開しています。

#454 で 2018/9/16 時点の デイリービルドを組み込んだ PR を投げました。

**Comment by m-tmatma** [comment]
#454 で対応した。

残件: サクラエディタリリース時点で最新の Universal ctags に差し替える

**Comment by m-tmatma** [comment]
最新版を取り込むタスクは #515 に分離して閉じます。
